### ISSUE TITLE
Unable to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by foosinn** [TeamSpeak-Systems/ts3init_linux_netfilter_module#18]
Errormessage:

```
/usr/src/ts3init-latest/src/ts3init_match.c: In function ‘calculate_cookie’:
/usr/src/ts3init-latest/src/ts3init_match.c:144:16: error: ‘const struct xt_action_param’ has no member named ‘family’
     switch (par->family)
                ^~
/usr/src/ts3init-latest/src/ts3init_match.c:177:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
```
