### PR TITLE
Changes for Ubuntu 18.04

### LINKED ISSUE #18: Unable to build on Ubuntu 18.04
Errormessage:

```
/usr/src/ts3init-latest/src/ts3init_match.c: In function ‘calculate_cookie’:
/usr/src/ts3init-latest/src/ts3init_match.c:144:16: error: ‘const struct xt_action_param’ has no member named ‘family’
     switch (par->family)
                ^~
/usr/src/ts3init-latest/src/ts3init_match.c:177:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
```

### LINKED ISSUE #19: Unable to install on Ubuntu 18.04
xtables libraries dir has changed from `install: target '/lib/xtables/' is not a directory: No such file or directory
` to `/usr/lib/x86_64-linux-gnu/xtables`.

```
install -g root -o root -m 644 libxt_ts3init.so libxt_ts3init_get_cookie.so libxt_ts3init_get_puzzle.so libxt_TS3INIT_RESET.so libxt_TS3INIT_SET_COOKIE.so libxt_TS3INIT_GET_COOKIE.so /lib/xtables/
install: target '/lib/xtables/' is not a directory: No such file or directory
Makefile.xtables:9: recipe for target 'install' failed
```

### PR DESCRIPTION
**Pull request by foosinn**
We did today a testsetup with Ubuntu 18.04. I wasn't able to compile the modules. I was able to do a few quick fixed. The module builds and seems to work fine.

Please review the changes, they might need some if/else handling to build on older kernel versions. I'm not really into c, so help is welcome.

fixes #18 
fixes #19

### CODE REVIEW

File: src/Makefile.xtables [hunk 1]
```diff
@@ -6,7 +6,11 @@ clean:
 	rm -f $(LIBS)
 
 install:
-	install -g root -o root -m 644 $(LIBS) /lib/xtables/
+	if [ -d /usr/lib/x86_64-linux-gnu/xtables ]; then \
+      install -g root -o root -m 644 $(LIBS) /usr/lib/x86_64-linux-gnu/xtables; \
+    else \
+      install -g root -o root -m 644 $(LIBS) /lib/xtables/ ; \
+    fi
```
Comment (muenchow) [inline src/Makefile.xtables]: please change it so that the default directory is /lib/xtables/ not  /usr/lib/x86_64-linux-gnu/xtables.
also fix indentation please.

File: src/compat_xtables.h [hunk 2]
```diff
@@ -90,7 +90,7 @@ static inline void proc_remove(struct proc_dir_entry *de)
 static inline struct net *par_net(const struct xt_action_param *par)
 {
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 4, 0)
-    return par->net;
+    return xt_net(par);
```
Comment (muenchow) [inline src/compat_xtables.h]:
```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 10, 0)
..
#elif LINUX_VERSION_CODE >= KERNEL_VERSION(4, 4, 0)
..
#endif
```

File: src/ts3init_match.c [hunk 3]
```diff
@@ -141,7 +141,7 @@ static inline __u8* get_payload(const struct sk_buff *skb, const struct xt_actio
 static int calculate_cookie(const struct sk_buff *skb, const struct xt_action_param *par, 
                        struct udphdr *udp, __u64 k0, __u64 k1, __u64* out)
 {
-    switch (par->family)
+    switch (xt_family(par))
```
Comment (muenchow) [inline src/ts3init_match.c]: syntax changed with version 4.10.0, please add a version ifdef like in compat_xtables.h

File: src/ts3init_target.c [hunk 4]
```diff
@@ -47,7 +47,7 @@ ts3init_send_ipv6_reply(struct sk_buff *oldskb, const struct xt_action_param *pa
     struct udphdr *udp;
     struct flowi6 fl;
     struct dst_entry *dst = NULL;
-    struct net *net = dev_net((par->in != NULL) ? par->in : par->out);
+    struct net *net = dev_net((xt_in(par) != NULL) ? xt_in(par) : xt_out(par));
```
Comment (muenchow) [inline src/ts3init_target.c]: syntax changed with version 4.10.0, please add a version ifdef like in compat_xtables.h

**Review by muenchow — CHANGES_REQUESTED** [review]
patch works, but breaks backwards compatibility.

File: src/compat_xtables.h (hunk 2 above)
Comment (foosinn) [reply src/compat_xtables.h]: done

File: src/ts3init_match.c (hunk 3 above)
Comment (foosinn) [reply src/ts3init_match.c]: done

File: src/ts3init_target.c (hunk 4 above)
Comment (foosinn) [reply src/ts3init_target.c]: done

**Review by foosinn — COMMENTED** [review]
updated, as you requested. also fixed the install on 32bit stretch+bionic

**Comment by muenchow** [comment]
`#include <linux/version.h>` line is missing in src/ts3init_match.c

**Comment by muenchow** [comment]
merged, thank you for providing these fixes.
